---

# # 1. Installation and prerequisites
# - name: Include installation tasks
#   ansible.builtin.include_tasks: install.yml

# # 2. Folder preparation
# - name: Include folder preparation tasks
#   ansible.builtin.include_tasks: folders.yml


# # 4. Nginx-specific tasks
# - name: Include nginx tasks
#   ansible.builtin.include_tasks: nginx.yml

# 5. Certificate management
- name: Include certificate management tasks
  ansible.builtin.include_tasks: certs.yml

- name: Include configuration tasks
  ansible.builtin.include_tasks: configuration.yml

# 7. Post-renewal actions
- name: Include post-renewal actions
  ansible.builtin.include_tasks: postactions.yml

# 8. Debugging and validation
- name: Include debugging tasks
  ansible.builtin.include_tasks: debug.yml
